### PR TITLE
Pass -thread to C files as well

### PR DESCRIPTION
**Pull request by diml**
This is to fix [PR#6809](http://caml.inria.fr/mantis/view.php?id=6809).

### CODE REVIEW

**Comment by gildor478** [comment]
The change seems fine, but I have one extra request:
Does one of the test fails with ocamlbuild >= 4.03 and is fixed by this change ?
OR
Can you add a test that will break with >= 4.03 and will be fixed by this change ?

(so that we can track any kind of regression in the future)

**Comment by diml** [comment]
At the moment every package depending on threads, using oasis and having C stubs fail to build with ocaml>=4.03 because of this. I don't think there is a test for this, I can try to add one when I get the time.

**Comment by gasche** [comment]
Where are we on this issue? The change in [PR#6809](http://caml.inria.fr/mantis/view.php?id=6809) was reverted from the 4.02.3 release, but kept in trunk, so it should be part of the 4.03 coming in early 2016. It would be nice if oasis could be fixed by then.

**Comment by diml** [comment]
I added a test. The test should fail with OCaml >= 4.03 and pass with the proposed patch. I cheched that the test passes with OCaml 4.02.3: none of `-package` or `-threads` are passed by ocamlbuild to C files so ocamlfind doesn't complain. I didn't check with trunk as oasis tests requires batteries which doesn't build with trunk.

**Comment by gasche** [comment]
Thanks, I'll try to fix batteries-in-trunk as soon as possible.

**Pull request merged**
