### PR TITLE
README: add link to issue tracker

### PR DESCRIPTION
**Pull request by seliopou**

### CODE REVIEW

**Comment by gildor478** [comment]
Thank you for your contribution. This file should actually be autogenerated (just as README.txt is). I would prefer to add a field IssueTracker, just as [Homepage](http://oasis.forge.ocamlcore.org/MANUAL.html#package).

If you have some spare cycle, it would be nice to modify your PR to do, otherwise, I'll have a look later.

**Comment by seliopou** [comment]
It seems as if there is already a [`BugReports`](https://github.com/ocaml/oasis/blob/master/src/oasis/OASISPackage_intern.ml#L344-L351) field that isn't actually exposed to the user. I unfortunately aren't familiar enough with the code to get it working.

**Comment by gildor478** [comment]
The field BugReports comes from this commit:
https://github.com/ocaml/oasis/commit/21eea065f41a09e437ecb5c76b1064231ef8354a

This is not yet in the latest version of OASIS, however it is missing the autogeneration part, that should be implemented here:
https://github.com/ocaml/oasis/blob/master/src/plugins/extra/stdfiles/StdFilesPlugin.ml#L549

The file this PR is changing, should actually be autogenerated by this precise plugin. Maybe the PR should be changed to just output this extra line in README ?

**Comment by gildor478** [comment]
This change da5bdbc6e5563d78f236271a9e14352db5caa582 add BugReports to _oasis and will automatically appear with the next release of OASIS.

**Pull request closed without merging**
