### PR TITLE
Fixing remaining omake issues

### PR DESCRIPTION
**Pull request by gerdstolpmann**
in particular the TODOs in the test

### CODE REVIEW

**Comment by gildor478** [comment]
Squashed and merged:
https://github.com/ocaml/oasis/commit/edaa05835a00aa514a556703fb0b7cace3426de7

**Comment by gildor478** [comment]
@gerdstolpmann bin-annot is only available since OCaml 4.01.

Can you check OCaml version before adding the -bin-annot flag ?

**Comment by gildor478** [comment]
https://travis-ci.org/ocaml/oasis/jobs/132473324

**Comment by gerdstolpmann** [comment]
Sure can add a check.

Note that the next omake release will require OCaml-4.02 as minimum for building omake (but keep in mind it will take at last 6 months from now to finish it, and even 4.02 will be quite old at that time). I see little value in supporting ancient versions like 3.12.

**Comment by gildor478** [comment]
We can actually enforce "OCamlVersion: >= 4.02" when the OMake plugin is present.

The side effect is that any _oasis that will use the OMake plugin will require to have a minimum OCaml version of 4.02. If you want to migrate old code base using OMake, you will have to restrict it to OCaml > 4.02.

What is you opinion on this ?

N.B. it is better to enforce the constraint now rather than once published in version 0.4.7

**Comment by gildor478** [comment]
Done for >= 4.01 here:
https://github.com/ocaml/oasis/commit/0ef5e5ee93fa165d6597578d54eea46fd47d37f9

**Pull request closed without merging**
