### PR TITLE
Fix dynamic mode setup under Cygwin

### PR DESCRIPTION
**Pull request by Chris00**

### CODE REVIEW

**Comment by Chris00** [comment]
I have activated testing of this project [under Cygwin](https://github.com/ocaml/oasis/commit/68ef535d3e8241f40f2203825a87f5cbe2e1eac2).  However, [using dynamic mode](https://github.com/ocaml/oasis/commit/343c01f8c82cd65fc31e13521453274f6df6c403), it is [failing](https://ci.appveyor.com/project/Chris00/oasis/build/1.0.24#L1216). This PR [fixes the problem](https://ci.appveyor.com/project/Chris00/oasis/build/1.0.25#L1216) but I am not confident that it is the right thing to do.  @gildor478 may you comment — especially on the purpose of `OASISHostPath.to_unix` and why it may fail?

**Comment by Chris00** [comment]
@gildor478 Ping?

**Comment by gildor478** [comment]
I am trying to integrate other things right now, this is in the batch for the next release... Will merge when I have fixed some other things.

**Comment by gildor478** [comment]
My guess is that the filename that causes an exception may be a mix of \ and /, which is probably seen as incorrect.

Do you have a filename example?

It would be better to track the source of the error (although your fix is a safe bet as well).

**Comment by aantron** [comment]
I seem to be having this issue as well. Here's a log: https://ci.appveyor.com/project/aantron/lwt/build/14/job/jb8ukp3e3v9v4prf#L2379

**Comment by gildor478** [comment]
The solution d3f541978dc6ff79060e439cd9b1383f245b655c
Actually, we were not processing correctly when Sys.os_type = "Cygwin". The build is green now.

**Comment by aantron** [comment]
Thank you!

**Comment by Chris00** [comment]
On 2016-06-24, Sylvain Le Gall wrote:
> 
> The solution d3f5419
> Actually, we were not processing correctly when Sys.os_type = 
> "Cygwin". The build is green now.

Great!  Congrats!

**Pull request closed without merging**
