### PR TITLE
[wip] cleanup, use ocp-indent, remove deps

### PR DESCRIPTION
**Pull request by c-cube**
This is a work in progress, do not merge for now. It builds on #80.

- [x] add some utils, factor code
- [x] add a `merlin` file
- [x] embed ocamlify, ocamlmod in `src/tools/`
- [x] embed `ocaml-data-notation` as `OASISData_notation`, add some combinators
- [x] replace every use of `with odn` by a hand-written `OASISData_notation` converter
- [ ] use [oasis-parser](https://github.com/c-cube/oasis-parser) instead of the current parser
- [ ] rebase on master
- [ ] ensure that tests pass, and regenerate oasis files properly

It is not up to date to master because it started 2 weeks ago.

### CODE REVIEW

**Comment by gildor478** [comment]
Concerning the project of oasis-parser:
- We need draw a clear line of what should migrate from oasis to oasis-parser. I think there are some pieces of code worth moving along but we need to know what. What is your take on that ?

- You should rename Oasis_x.. to OASISX.. to follow naming scheme of oasis project

- I am trying to enforce a new "policy", if it is a library we should put it in src/lib/oasis-parser

- I would like to transfer some tests and use OUnit, do you agree ?

- Why not use simple yacc/lex parser ?

**Comment by gildor478** [comment]
I am pretty interested in your hand written OASISData_notation, that may replace part of what I am trying to do to get rid of it. Can you easily split this part out of your current PR?

**Comment by c-cube** [comment]
About oasis-parser, I wanted to have a separated parser for, possibly, other projects to use. I can rename modules if you want (although it might collide with oasis' namespace, especially `Oasis_ast`). I wanted a lex/yacc parser but could not make it work because, I think, the grammar `_oasis` is not context-free (lines must be parsed differently depending on their indentation and the presence of `if` or `Name:`). A handwritten lexer could probably make it, but imho it would be as complicated as my current solution.

About `OASISData_notation`, well, it was the most painful part of this PR :). I cannot really separate it from the ocp-indentation unless I re-do all the work, sadly. Is it problematic to merge the 4 commits (once I rebase on master)?

**Comment by gildor478** [comment]
Merlin + OCP indent -> no problems
ocamlify/ocamlmod -> still have my concerns and would like to postpone it a bit (I don't say no, just need time to think about it)

Also if possiblem could you use OASISDataNotation ? 

I tend to use _ for closely related stuff (OASISVersion, OASISVersion_lexer...).

**Comment by bluddy** [comment]
@c-cube, is there no existing parser combinator library?

**Comment by c-cube** [comment]
@bluddy I didn't want more dependencies if possible, and they all look either too naive (w.r.t backtracking or tailrec) or had regex dependencies themselves. It's pretty simple to write anyway.

**Comment by bluddy** [comment]
@c-cube: hey man -- you're the Containers dev. I trust your work.

BTW, were you the one who created the gitter.im room for oasis? If so, can you create a page for ocaml in general? And maybe ocamlbuild too?

**Comment by gildor478** [comment]
@c-cube since most of the things on this list has been implemented I think you can close this PR.

The only remaining points not implemented are ocamlify/ocamlmod removal and I propose to rediscuss this point later.

**Pull request closed without merging**
