### PR TITLE
Documentation Cleanup

### PR DESCRIPTION
**Pull request by RadicalZephyr**
I went through and corrected the grammar, spelling and formatting of Oasis's documentation.  I tried to preserve the intention of the words, I apologize if I made any mistakes in that regard.

### CODE REVIEW

**Comment by Chris00** [comment]
I read the corrections and they look fine to me.
@gildor478 Any reason to hold the merge of this?

**Comment by gildor478** [comment]
There are pending conflicts right now. Need to resolve them by hand.

**Comment by Chris00** [comment]
@RadicalZephyr I know you contributed this a long time ago but would you accept to rebase your contribution on the current *master* branch?

**Comment by RadicalZephyr** [comment]
Yes, I can do that tomorrow afternoon.

**Comment by Chris00** [comment]
@RadicalZephyr Thank you!

**Comment by RadicalZephyr** [comment]
@Chris00 and @gildor478 I've rebased the documentation changes.  I didn't rebuild the project files because I couldn't get it to work (I completely forget what I did last time).

**Comment by Chris00** [comment]
On Mon, 17 Aug 2015 13:24:56 -0700, Geoff Shannon wrote:
> 
> @Chris00 and @gildor478 I've rebased the documentation changes.

Thanks.

> I didn't rebuild the project files because I couldn't get it to work (I completely forget what I did last time).

That's OK.

**Pull request merged**
