### PR TITLE
Fix: no_automatic_syntax must not disable the -package injection logic

### PR DESCRIPTION
**Pull request by cakeplus**
The bug affected [pa_comprehension](https://github.com/cakeplus/pa_comprehension), for which I needed to specify the `_tags` manually, since it requires `camlp4r` instead of `camlp4o`.

@jpdeplaix, can you confirm that I haven't broken anything with my fix?

### CODE REVIEW

**Comment by jpdeplaix** [comment]
I don't understand what it is fixing :/ Are you using ocaml < 3.12.1 ?

**Comment by cakeplus** [comment]
No, I'm using the latest OCaml.

The problem is that `no_automatic_syntax` completely disabled injection of `-package` flags instead of merely disabling `-syntax camlp4o`. See [pa_comprehension](https://github.com/cakeplus/pa_comprehension) for a simple example. Do `make setup` and try building it -- the syntax extension won't build because it depends on findlib packages.

**Comment by jpdeplaix** [comment]
Mmh I see the problem. I've not seen this because I've enforced the compiler version to be >= 3.12.1 which on recent oasis versions use only the "new" (rather old now) syntax for packages `package(foo)` and not the old trick `pkg_foo`.
But the thing I'd rather prefer to merge #46 than this one. The pkg_ is really ugly and almost nobody is using ocaml < 3.12.1 by now (especially not with an up-to-date oasis version).

**Comment by cakeplus** [comment]
If I understood it correctly, the problem is not related at all to the `pkg`/`package` dichotomy or compatibility with 3.12.1, as it's all about automatic detection of when to use `-syntax camlp4o` (which fails in my case, as I need `camlp4r`). `no_automatic_syntax` is a useful workaround -- I've only fixed a simple bug in its implementation (to no surprise -- it is an AlphaFeature, after all).

**Comment by jpdeplaix** [comment]
Mmmh I don't understand what you are saying :/
I tried with pa_comprehension and it works fine if you set OCamlVersion to >= 3.12.1. After an `oasis setup` I got this diff:
```
diff --git a/_oasis b/_oasis
index 8f7b6dd..45bd899 100644
--- a/_oasis
+++ b/_oasis
@@ -10,7 +10,7 @@ XStdFilesREADME : false
 BuildTools      : ocamlbuild, camlp4
 Homepage        : https://github.com/cakeplus/pa_comprehension
 OASISFormat     : 0.4
-OCamlVersion    : >= 3.11
+OCamlVersion    : >= 3.12.1
 AlphaFeatures   : no_automatic_syntax
 
 Description:
diff --git a/_tags b/_tags
index 45b9cfe..180516c 100644
--- a/_tags
+++ b/_tags
@@ -1,5 +1,5 @@
 # OASIS_START
-# DO NOT EDIT (digest: 3f1a18172fa77801e882ed3c9e75c8c1)
+# DO NOT EDIT (digest: 31678e17c620fcd722246e1f3223f4e2)
 # Ignore VCS directories, you can use the same kind of rule outside
 # OASIS_START/STOP if you want to exclude directories that contains
 # useless stuff for the build process
@@ -16,9 +16,9 @@ true: annot, bin_annot
 "_darcs": not_hygienic
 # Library pa_comprehension
 "src/pa_comprehension.cmxs": use_pa_comprehension
-<src/*.ml{,i,y}>: pkg_camlp4.extend
-<src/*.ml{,i,y}>: pkg_camlp4.lib
-<src/*.ml{,i,y}>: pkg_camlp4.quotations
+<src/*.ml{,i,y}>: package(camlp4.extend)
+<src/*.ml{,i,y}>: package(camlp4.lib)
+<src/*.ml{,i,y}>: package(camlp4.quotations)
 # OASIS_STOP
 
 <src/*.{ml,mli}>: syntax_camlp4r
```
And it works fine.
Sorry if I'm missing your point.

**Comment by jpdeplaix** [comment]
Ping

**Comment by cakeplus** [comment]
Pong.

Sorry for a delay. I just found the time to investigate the matter more thoroughly.

> I tried with pa_comprehension and it works fine if you set OCamlVersion to >= 3.12.1.

It indeed does, to my surprise; so setting the version to 3.12.1 is a viable workaround. Still, there is a bug in the implementation of `no_automatic_syntax` that affects the earlier versions of OCaml.

> Sorry if I'm missing your point.

The point is that enabling `no_automatic_syntax` must not disable the `pkg_*` flags that are necessary for OCaml < 3.12.1. I simply moved the condition that checks for `conf.no_automatic_syntax` a bit more closer to the associated logic (injecting `-syntax camlp4o`). Having carefully checked the implementation of the OCamlBuild plugin, I conclude the change being safe to be merged.

**Comment by jpdeplaix** [comment]
Oh I see. Well, to be honnest, I think I did this alpha feature with my use case only in mind. So yeah it should have been two sparated things. I'm not available to do that right now but I'll try to do something when I'll be available.
Meanwhile, I think this fix should be ok. Maybe you can add this to the big if "&& ocamlversion < 3.12.1" ? But I'm not sure if we really want that.
The thing is: I've probably did that because I don't like the pkg_* trick.

**Comment by cakeplus** [comment]
> Maybe you can add this to the big if "&& ocamlversion < 3.12.1" ?

But why? It works just fine with any version now (hopefully).

> The thing is: I've probably did that because I don't like the pkg_* trick.

I don't like it either; and perhaps the way to go, in the long term, is to drop support for it altogether (and require OCaml >= 3.12.1). It doesn't complicate the implementation much, though.

**Comment by jpdeplaix** [comment]
Mmh oh ok, never mind. I was thinking it was the default behaviour with ocaml >= 3.12.1 but no. Yeah I'm ok to merge this then. Sylvain ?

**Comment by gildor478** [comment]
Thanks for the fix.

As a matter of taste I do prefer when you have at least one test that demonstrates the bug and the fix. This helps to prevent accidental regression and improve the quality overall.

@cakeplus is it possible to add some sort of test that this PR fixes ?

Except for the test, I am fine submitting the PR.

**Comment by cakeplus** [comment]
> @cakeplus is it possible to add some sort of test that this PR fixes?

Sure. I'll find time for this later (a bit busy right now).

**Comment by cakeplus** [comment]
I've added a simple test case -- the best I could do without spending much time on learning the ins and outs of the rather intricate test system.

**Comment by jpdeplaix** [comment]
Sylvain ?

**Pull request merged**
