### PR TITLE
Add MinGW OCaml 4.03 build to AppVeyor

### PR DESCRIPTION
**Pull request by aantron**
This is currently a wrapper around @fdopen's opam-repository-mingw. See https://fdopen.github.io/opam-repository-mingw/.

May take a few tries to get it working right.

### CODE REVIEW

**Comment by aantron** [comment]
I'm guessing the [current build failure](https://ci.appveyor.com/project/gildor478/oasis/build/1.0.135/job/t1un5shftdvh843s#L1359) on MinGW is due to an `.exe` suffix. @gildor478? The build log looks promising otherwise.

Should note that the MinGW build is running in Cygwin, but the output is native binaries.

**Comment by gildor478** [comment]
It is either missing .exe or because the Main.native is not copied into the top source directory (this should be a link but links are disabled on Windows -- but not Cygwin).

Actually what you can try is to use "oasis" rather than "Main.native" because this is the binary that we install right before and it should be available. Given the fact that oasis and oasis.EXE will make no difference, it should work in Cygwin and MinGW case.

Can you change your PR to do that...

**Comment by aantron** [comment]
The new `appveyor.yml` also is not installing Camlp4, since OASIS apparently does not depend on it anymore. However, I just looked at examples. Is it better to keep installing Camlp4?

**Comment by gildor478** [comment]
No need to install camlp4, we should be able to get rid of it.

I am more concerned by the fact that 'oasis' was not working. This is probably worth investigating.

appveyor_build.sh belongs to src/tools/ci/, feel free to move it there.

**Comment by aantron** [comment]
Ok. I am not prepared to investigate, though I can perhaps do it later. If you want to investigate before merging this PR, I have no objection to you taking the commits over into your own branch, and doing whatever is necessary.

**Comment by gildor478** [comment]
This will have to wait the 0.4.8 release (top priority for now). I'll have a look after the release.

**Comment by gildor478** [comment]
I have reworked the appveyor file to work correctly with MingW.

**Pull request closed without merging**
