### PR TITLE
Fixed linking issue caused by missing program tag

### PR DESCRIPTION
**Pull request by mmottl**

### CODE REVIEW

**Comment by gildor478** [comment]
This is somehow reverting 
https://github.com/ocaml/oasis/commit/cb96135a13b3a7f6876f5bbd217fd19dc7f44737

One way or another, that would be nice to have a test case that would make clear the problem addressed (should have been done the first time actually).

**Comment by mmottl** [comment]
@gildor478 the problem I have with the current version is that Lacaml won't build a correct library.  If an OPAM user tries to link with Lacaml, there will be a linking error.  Interestingly, the problem doesn't happen when merely building the Lacaml examples together with the library.

**Comment by gildor478** [comment]
Maybe you can try to build a test, like one present in this file.
https://github.com/ocaml/oasis/blob/master/test/TestFull.ml

I'll encourage you to try try_installed_exec/library to see if you can pinpoint the precise case where the problem appears (without your patch) and that your patch will solve.

**Comment by mmottl** [comment]
@gildor478 I'm afraid, I don't have time to implement such a test case right now.  If I ever run into the problem again, I'll investigate this more deeply.

**Pull request closed without merging**
